### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by kalodis** [Druidmaciek/OutlookEmailCreator#1]
I have a list of proxies, would that be something that you could add as support? Im new to python so its a bit tricky for me...

**Comment by Druidmaciek** [comment]
Hi, just added support for authenticated proxies in <user>:<password>@<ip>:<port>

**Comment by kalodis** [comment]
Thanks. So im seeing here in the code 

`class Proxies:
    proxy_list = []

    @staticmethod
    def load_proxies(file_path: str):`

proxy_list = [] 


inside the brackets we will need to define the path to where our proxy list is stored correct?

ex: c:\users\username\desktop\proxy_list.txt

**Comment by Druidmaciek** [comment]
Nope.
before you initiate OutlookAccountCreator class you call the load_proxies function with the path as file_path argument and set use_proxy to True when calling OutlookAccountCreator
`    
# Load proxies from file
    Proxies.load_proxies('proxies.txt')
    # Initialize account creator class
    account_creator = OutlookAccountCreator(use_proxy=True)
    # Run account creator
    account_creator.create_account()
`

**Comment by kalodis** [comment]
Ah ok again i do apologize as I am still learning python. 

# Load proxies from file
Proxies.load_proxies('proxies.txt') <---- Here is where you define the location of the proxy list correct?
ex: c:\users\username\desktop\proxy_list.txt

**Comment by Druidmaciek** [comment]
yeah

**Comment by kalodis** [comment]
Great! Thank you Druidmaciek. I may reach out to you for a project in Python. Im stumped on where to get started but still looking before i reach out!

**Comment by Druidmaciek** [comment]
Sure feel free to reach out. I am closing the issue now.
